title: SEO Blog Automation
description: Automated electronics deal blog posts
baseurl: "/seo-blog-automation"
url: "https://Jai-Keshav-Sharma.github.io"

theme: minima

markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-seo-tag

collections:
  posts:
    output: true
    permalink: /:year/:month/:day/:title/
